### ISSUE TITLE
No input button for selecting duration of the task in add task page

### ISSUE THREAD

**Issue by whogurdevil** [Algorithmics001/Atomic_Tasker#41]
Duration is currently shown zero for every task in view task page ....  we cant use more hooks than a certain value , learn react native hooks for further problems...

**Comment by RaghavJit** [comment]
Duration button was added and hooks were created for taking input.

**Comment by RaghavJit** [comment]
A Modal needs to be created to take input for 'duration' field

**Comment by RaghavJit** [comment]
A Modal needs to be created to take input for 'duration' field

**Comment by RaghavJit** [comment]
Button is functional now and takes input
